# Site settings
title: Fabio Ellger
email: fabio.ellger@wzb.eu
description: >- 
  Research Fellow  
twitter_username: fabioellger
github_username: fabioellger
minimal_mistakes_skin: air #alternative is 'contrast'
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 0 # amount of posts to show

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-EQP1E228G8" #"UA-161691340-1" # You'll need to update this to the "G-" format tracking ID for Google Analytics 4
    anonymize_ip: false

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

# Author information
author:
  name   : "Dr. Fabio Ellger"
  avatar : "/assets/images/Foto_Ellger.jpg"
  bio    : "Postdoctoral Research Fellow\nTransformations of Democracy Unit\nWZB Berlin Social Science Center\nfabio.ellger[at]wzb.eu"
  links:
    - label: "[Curriculum Vitae]"
      icon: "fas fa-file"
      url: "https://www.fabioellger.com/assets/docs/CV_Ellger.pdf"
    - label: "[Twitter]"
      icon: "fab fa-twitter"
      url: "https://twitter.com/fabioellger"

# Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/fabioellger"

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
